### ISSUE TITLE
ldconfig: /usr/lib32/libSPIRV-Tools-shared.so is not a symbolic link

### ISSUE THREAD

**Issue by corecontingency** [Frogging-Family/spirv-tools-git#1]
I just installed this `spirv-tools-git` package. Now, every time I install/upgrade any package with pacman, this error pops up:

```
:: Processing package changes...
(1/1) upgrading winetricks-git                                        [#######################################] 100%
ldconfig: /usr/lib32/libSPIRV-Tools-shared.so is not a symbolic link

ldconfig: /usr/lib/libSPIRV-Tools-shared.so is not a symbolic link

:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Updating icon theme caches...
(3/4) Updating the desktop file MIME type cache...
(4/4) Performing snapper post snapshots for the following configurations...
==> root: 914
```

It seems like the problem is caused by this package, see:

```
user@linuxlaptop ~> pacman -Qo /usr/lib/libSPIRV-Tools-shared.so
/usr/lib/libSPIRV-Tools-shared.so is owned by spirv-tools-tkg-git 2020.4.r67.gc20995ef-1
```

```
user@linuxlaptop ~> pacman -Qo /usr/lib32/libSPIRV-Tools-shared.so
/usr/lib32/libSPIRV-Tools-shared.so is owned by lib32-spirv-tools-tkg-git 2020.4.r67.gc20995ef-1
```

Maybe caused by commit 81ad952d4e3e3f242aef5a71f2415bf56d0bc3ce? It's really not that big of a deal, but it hits my OCD hard. :)

Is there any way to prevent this error from popping up every time I use pacman? Thank you!

**Comment by Tk-Glitch** [comment]
Maybe the upstream issue was fixed since that commit. I'll have a look.

**Comment by ronoverdrive** [comment]
I've been getting the same error for a while now. So far it hasn't caused any issues, but yeah its annoying to see that error.
