### ISSUE TITLE
lipSPIRV-Tools.so and libSPIRV-Tools-opt.so Don't Exist in This Package but do in the Official Arch Package, Missing those libs breaks MPV 

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/spirv-tools-git#2]
When trying to run MPV with hw acceleration on, I get an error:

```
mpv: error while loading shared libraries: libSPIRV-Tools.so: cannot open shared object file: No such file or directory
```
As spirv-tools-tkg-git only provides /usr/lib{32}/libSPIRV-Tools-shared.so

If I symlink it to /usr/lib/libSPIRV-Tools.so, it gives me another error:

```
mpv: error while loading shared libraries: libSPIRV-Tools-opt.so: cannot open shared object file: No such file or directory
```
So it seems there are at least two .so files that are missing from this package but not official spirv-tools from extra.

If there's no way to include those files, is there any solution to this issue?

**Comment by netbospl** [comment]
I did had same issue, but it's gone now. Now error I'm getting useing HW accelerated mpv is
plexmediaplayer: symbol lookup error: /usr/lib/libshaderc_shared.so.1: undefined symbol: _ZN8spvtools9Optimizer28RegisterVulkanToWebGPUPassesEv

Tried to rebuild mpv during which I've received
When: [294/504] Compiling video/out/opengl/context_wayland.c
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libshaderc_combined.a(compiler.cc.o): undefined reference to symbol '_ZN7glslang7TShader16setHlslIoMappingEb'
/usr/bin/ld: /usr/lib/libglslang.so.11: error adding symbols: DSO missing from command line

Is it relating to same issue or should I open new ticket? @Tk-Glitch

**Comment by Tk-Glitch** [comment]
That error is different indeed. However it doesn't seem to be directly related to spirv-tools. It seems to be libglslang or shaderc related, which might need to be git versions as well to work with spirv-tools-git. A new ticket would be cool for sure.

**Comment by kesabarana543-art** [comment]
mpv: error while loading shared libraries: libSPIRV-Tools.so: cannot open shared object file: No such file or directory

**Comment by Tk-Glitch** [comment]
> mpv: error while loading shared libraries: libSPIRV-Tools.so: cannot open shared object file: No such file or directory

Just built the packages on my end to check. Lib is present. Mpv works just fine.
Make sure you have installed both. It's a split package, so makepkg outputs two, both lib32 and lib64 packages.

<img width="483" height="359" alt="Image" src="https://github.com/user-attachments/assets/5d0a96d0-96a8-4d12-86e1-c8f96ee16a5c" />
